### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by shadow44g4** [chatwoot/chatwoot#10860]
### Describe the bug

I'm trying to install chatwoot on a VM in Azure (Ubuntu 22LTS) but every time I get an error in the VITE installation and some PNPM errors, this is happening after Chatwoot version 4, how to proceed?

```
Hit:1 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://packages.microsoft.com/repos/microsoft-ubuntu-jammy-prod jammy InRelease
Hit:6 https://deb.nodesource.com/node_20.x nodistro InRelease
Get:7 http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease [129 kB]
Hit:8 https://packages.redis.io/deb jammy InRelease
Get:9 http://apt.postgresql.org/pub/repos/apt jammy-pgdg/16 amd64 Packages [2604 B]
Fetched 132 kB in 1s (154 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
autoconf is already the newest version (2.71-2).
build-essential is already the newest version (12.9ubuntu3).
g++ is already the newest version (4:11.2.0-1ubuntu1).
gcc is already the newest version (4:11.2.0-1ubuntu1).
libffi-dev is already the newest version (3.4.2-4).
libgdbm-dev is already the newest version (1.23-1).
libgdbm6 is already the newest version (1.23-1).
libgmp-dev is already the newest version (2:6.2.1+dfsg-3ubuntu1).
liblzma-dev is already the newest version (5.2.5-2ubuntu1).
libreadline-dev is already the newest version (8.1.2-1).
libyaml-dev is already the newest version (0.2.2-1build2).
patch is already the newest version (2.7.6-7build2).
ruby-dev is already the newest version (1:3.0~exp1).
libvips42 is already the newest version (8.12.1-1build1).
ca-certificates is already the newest version (20240203~22.04.1).
file is already the newest version (1:5.41-3ubuntu0.1).
git is already the newest version (1:2.34.1-1ubuntu1.12).
libncurses5-dev is already the newest version (6.3-2ubuntu0.1).
libssl-dev is already the newest version (3.0.2-0ubuntu1.18).
libxml2-dev is already the newest version (2.9.13+dfsg-1ubuntu0.5).
libxslt1-dev is already the newest version (1.1.34-4ubuntu0.22.04.1).
software-properties-common is already the newest version (0.99.22.9).
sudo is already the newest version (1.9.9-1ubuntu2.4).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu9.2).
gnupg2 is already the newest version (2.2.27-3ubuntu2.1).
imagemagick is already the newest version (8:6.9.11.60+dfsg-1.3ubuntu0.22.04.5).
python3-pip is already the newest version (22.0.2+dfsg-1ubuntu0.5).
nodejs is already the newest version (20.18.2-1nodesource1).
redis-tools is already the newest version (6:7.4.2-1rl1~jammy1).
libpq-dev is already the newest version (17.2-1.pgdg22.04+1).
postgresql-client-16 is already the newest version (16.6-1.pgdg22.04+1).
The following package was automatically installed and is no longer required:
  libllvm14
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

changed 1 package in 2s

1 package is looking for funding
  run `npm fund` for details
Reading package lists...
Building dependency tree...
Reading state information...
postgresql-contrib is already the newest version (14+238).
redis-server is already the newest version (6:7.4.2-1rl1~jammy1).
postgresql-16 is already the newest version (16.6-1.pgdg22.04+1).
postgresql-16-pgvector is already the newest version (0.8.0-1.pgdg22.04+1).
The following package was automatically installed and is no longer required:
  libllvm14
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
certbot is already the newest version (1.21.0-1build1).
python3-certbot-nginx is already the newest version (1.21.0-1).
nginx is already the newest version (1.18.0-6ubuntu14.5).
nginx-full is already the newest version (1.18.0-6ubuntu14.5).
The following package was automatically installed and is no longer required:
  libllvm14
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
1001
gpg: key 105BD0E739499BDB: 2 duplicate signatures removed
gpg: key 105BD0E739499BDB: "Piotr Kuczynski <piotr.kuczynski@gmail.com>" not changed
gpg: key 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 2
gpg:              unchanged: 2
gpg: key 105BD0E739499BDB: 2 duplicate signatures removed
gpg: key 105BD0E739499BDB: "Piotr Kuczynski <piotr.kuczynski@gmail.com>" not changed
gpg: key 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 2
gpg:              unchanged: 2
Downloading https://github.com/rvm/rvm/archive/1.29.12.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.12/1.29.12.tar.gz.asc
gpg: Signature made Fri Jan 15 18:46:22 2021 UTC
gpg:                using RSA key 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: Good signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7D2B AF1C F37B 13E2 069D  6956 105B D0E7 3949 9BDB
GPG verified '/usr/local/rvm/archives/rvm-1.29.12.tgz'
Upgrading the RVM installation in /usr/local/rvm/
Upgrade of RVM in /usr/local/rvm/ is complete.
  * Please do NOT forget to add your users to the <code>rvm</code> group.
     The installer no longer auto-adds root or users to the rvm group. Admins must do this.
     Also, please note that group memberships are ONLY evaluated at login time.
     This means that users must log out then back in before group membership takes effect!

<warn>Thanks for installing RVM 🙏</warn>
Please consider donating to our open collective to help us maintain RVM.

👉  Donate: <code>https://opencollective.com/rvm/donate</code>


The user `chatwoot' is already a member of `rvm'.
ERROR:  role "chatwoot" already exists
ALTER ROLE
ALTER ROLE
UPDATE 1
DROP DATABASE
CREATE DATABASE
UPDATE 1
You are now connected to database "template1" as user "postgres".
VACUUM
Synchronizing state of redis-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable redis-server
Synchronizing state of postgresql.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable postgresql
rvm 1.29.12 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
Already installed ruby-3.3.3.
To reinstall use:

    rvm reinstall ruby-3.3.3

Using /usr/local/rvm/gems/ruby-3.3.3
fatal: destination path 'chatwoot' already exists and is not an empty directory.
Already on 'master'
Your branch is up to date with 'origin/master'.
Bundle complete! 127 Gemfile dependencies, 318 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
2 installed gems you directly depend on are looking for funding.
  Run `bundle fund` for details
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your pnpm version is incompatible with "/home/chatwoot/chatwoot".

Expected version: 9.x
Got: 10.2.1

This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.

To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
I, [2025-02-06T20:40:52.482593 #337482]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:40:52.482661 #337482]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:40:52.614473 #337482]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your pnpm version is incompatible with "/home/chatwoot/chatwoot".

Expected version: 9.x
Got: 10.2.1

This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.

To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
-------------- Bulding SDK for Production --------------
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your pnpm version is incompatible with "/home/chatwoot/chatwoot".

Expected version: 9.x
Got: 10.2.1

This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.

To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
-------------- Bulding App for Production --------------
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your pnpm version is incompatible with "/home/chatwoot/chatwoot".

Expected version: 9.x
Got: 10.2.1

This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.

To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
Building with Vite ⚡️
I, [2025-02-06T20:40:57.626709 #337557]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:40:57.626754 #337557]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:40:59.698539 #337557]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-06T20:41:02.476210 #337631]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:02.476294 #337631]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:04.339618 #337631]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-06T20:41:07.120499 #337680]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:07.120547 #337680]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:08.931113 #337680]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-06T20:41:11.674180 #337698]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:11.675104 #337698]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:13.576008 #337698]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-06T20:41:16.483597 #337725]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:16.483652 #337725]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:18.350033 #337725]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-06T20:41:21.071005 #337743]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:21.071059 #337743]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:22.967591 #337743]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-06T20:41:25.743506 #337761]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:25.743562 #337761]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:27.655689 #337761]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-06T20:41:30.684935 #337780]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:30.684988 #337780]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:32.615089 #337780]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-06T20:41:36.690707 #337885]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:36.690755 #337885]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:38.978520 #337885]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-06T20:41:44.326564 #337903]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:44.326621 #337903]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:51.443871 #337903]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-06T20:41:54.154052 #337932]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:54.154100 #337932]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:41:55.992145 #337932]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-06T20:42:01.969516 #337952]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:42:01.969575 #337952]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:42:03.855583 #337952]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-06T20:42:08.647822 #338059]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:42:08.647876 #338059]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:42:12.748036 #338059]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-06T20:42:16.979387 #338085]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:42:16.979440 #338085]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:42:18.898156 #338085]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-06T20:42:24.993204 #338109]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:42:24.993274 #338109]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:42:26.905783 #338109]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-06T20:42:30.724352 #338129]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:42:30.724411 #338129]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:42:32.690278 #338129]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-06T20:42:36.276060 #338237]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:42:36.276119 #338237]  INFO -- : [dotenv] Loaded [33m.env[0m
I, [2025-02-06T20:42:38.745566 #338237]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
undefined
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command was killed with SIGKILL (Forced termination): vite build --mode production

pid 337666 exit 1
Build with Vite failed! ❌

pid 337562 exit 1
Build with Vite failed! ❌

pid 337543 exit 1
Build with Vite failed! ❌

```

### To Reproduce

SUDO SU
wget https://get.chatwoot.app/linux/install.sh
chmod +x install.sh
./install.sh --install

### Environment

Linux VM

### Cloud Provider

Azure

### Platform

None

### Operating system

UBUNTU 22.04 LTS ON AZURE

**Comment by Harukisatoh** [comment]
I just got the exact same error.

**Comment by willdotcom** [comment]
First 
`npm uninstall -g pnpm`

Second
`npm install -g pnpm@9`

and try again.

**Comment by vishnu-narayanan** [comment]
Hey, this was due to a `corepack` - `npm` registry issue. We have pushed a fix via https://github.com/chatwoot/chatwoot/pull/10840

We also have upgraded **cwctl**(`cwctl v3.2.0`) to handle this. Could you try again on a fresh instance ideally on Ubuntu 24.04?

**Comment by nemanja-z** [comment]
I tried installing today on Ubuntu 24.04, and the issue still exists. The same error appears during installation.

**Comment by scmmishra** [comment]
Can you confirm the version of PNPM you are using @nemanja-z? Also are you on the latest `cwctl` version?

**Comment by nemanja-z** [comment]
I'm using this [guide](https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm) for installation, and it seems that the script fails before installing cwctl. I just checked this pull request #10840, and it looks like the installation script still doesn't include the changes from that pull request. 
```This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
-------------- Bulding App for Production --------------
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your pnpm version is incompatible with "/home/chatwoot/chatwoot".

Expected version: 9.x
Got: 10.2.1

This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.

To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".

Your Node version is incompatible with "/home/chatwoot/chatwoot".

Expected version: 20.x
Got: v23.7.0

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
Building with Vite ⚡️
I, [2025-02-10T13:25:11.348737 #74718]  INFO -- : [dotenv] Loaded .env
I, [2025-02-10T13:25:11.348792 #74718]  INFO -- : [dotenv] Loaded .env
I, [2025-02-10T13:25:13.365587 #74718]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-10T13:25:16.346470 #74736]  INFO -- : [dotenv] Loaded .env
I, [2025-02-10T13:25:16.346520 #74736]  INFO -- : [dotenv] Loaded .env
I, [2025-02-10T13:25:18.613172 #74736]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-10T13:25:21.909635 #74755]  INFO -- : [dotenv] Loaded .env
I, [2025-02-10T13:25:21.909687 #74755]  INFO -- : [dotenv] Loaded .env
I, [2025-02-10T13:25:23.685485 #74755]  INFO -- : [rake ip_lookup:setup] IP_LOOKUP_API_KEY empty. Skipping geoip database setup
Building with Vite ⚡️
I, [2025-02-10T13:25:27.724853 #74773]  INFO -- : [dotenv] Loaded .env
I, [2025-02-10T13:25:27.725135 #74773]  INFO -- : [dotenv] Loaded .env
undefined
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command was killed with SIGKILL (Forced termination): vite build --mode production

pid 74704 exit 1
Build with Vite failed! ❌

**Comment by vishnu-narayanan** [comment]
could you share the output of `cwctl --version` ?

**Comment by nemanja-z** [comment]
Command 'cwctl' not found.

**Comment by shadow44g4** [comment]
> First `npm uninstall -g pnpm`
> 
> Second `npm install -g pnpm@9`
> 
> and try again.

Thank you very much for your help, I did this procedure and besides that I also edited the install.sh fixing the pnpm@9 version, I also removed the nodejs installation from the script and did the installation from the outside, thank you very much.

**Comment by maxihoster** [comment]
Same issue with Ubuntu 24.04! Impossible to install Chatwoot! Error during geoip .....

**Comment by AndersonAraujjo5** [comment]
> npm install -g pnpm@9

Resolveu o problema, rodei o

Primeironpm uninstall -g pnpm
Segundonpm install -g pnpm@9

E depois removi os script de instalaçao do nodejs e colorquei a verção do pnpm@9

![Image](https://github.com/user-attachments/assets/dada8d3a-ce73-46b5-ab08-90c4d190de2f)

**Comment by maxihoster** [comment]
I have try all the explaination here... but nothing work! Impossible to install Chatwoot anymore! Complicated...

**Comment by vishnu-narayanan** [comment]
Hey everyone, I was able to replicate this. This is due to the corepack issue and the fixes not being available in `4.0.1`.  This will be fixed once the February monthly release is out tomorrow.

As a workaround for now, please use `./install.sh --Install develop` to install. This will install the latest `develop` which is stable RC branch for Feb monthly release.

**Comment by miguelrochajr** [comment]
> Hey everyone, I was able to replicate this. This is due to the corepack issue and the fixes not being available in `4.0.1`. This will be fixed once the February monthly release is out tomorrow.
> 
> As a workaround for now, please use `./install.sh --Install develop` to install. This will install the latest `develop` branch, which is the stable release candidate(RC) branch for Feb monthly release.

Thanks for that. I'll check this up tomorrow.

**Comment by miguelrochajr** [comment]
> First `npm uninstall -g pnpm`
> 
> Second `npm install -g pnpm@9`
> 
> and try again.

Just a heads up for macOS developers:

If you have installed pnpm without npm, run "which pnpm" and find the place where it is installed.

When you run it, just perform a **rm -rf** in it.

**Comment by maxihoster** [comment]
Installation fail on all case! When a real fix will be deploy?

**Comment by bkonia** [comment]
> Hey everyone, I was able to replicate this. This is due to the corepack issue and the fixes not being available in `4.0.1`. This will be fixed once the February monthly release is out tomorrow.
> 
> As a workaround for now, please use `./install.sh --Install develop` to install. This will install the latest `develop` branch, which is the stable release candidate(RC) branch for Feb monthly release.

Tried this to no avail. see attached screenshots.

![Image](https://github.com/user-attachments/assets/69220d80-d27e-420d-be94-5b45f2bc45f4)

![Image](https://github.com/user-attachments/assets/84d7d2d2-d454-432a-8fc0-dc14d8f2aacd)

**Comment by vishnu-narayanan** [comment]
@bkonia Could you share more details?

1. OS  and version
2. `./install.sh --version`

Are you trying to install a fresh instance or upgrading an existing one?

Also, could you share the full log of `/var/log/chatwoot-setup.log`?

**Comment by bkonia** [comment]
> 1. OS  and version
Ubuntu 24.04.2 LTS

> 3. `./install.sh --version`
cwctl v3.2.0

> Are you trying to install a fresh instance or upgrading an existing one?
Fresh instance

> Also, could you share the full log of `/var/log/chatwoot-setup.log`?
[chatwoot-setup.log](https://github.com/user-attachments/files/19054537/chatwoot-setup.log)

**Comment by tchula** [comment]
Same problem here. I will try to install with docker instead

**Comment by capemsx** [comment]
Same problem here. Running recommended Ubuntu version with installation script v3.2.0.

**Comment by vishnu-narayanan** [comment]
@tchula 

Could you share more details?

    OS and version
    ./install.sh --version

Are you trying to install a fresh instance or upgrading an existing one?

Also, could you share the full log of /var/log/chatwoot-setup.log?

**Comment by vishnu-narayanan** [comment]
@capemsx 

Could you share more details?

    OS and version
    ./install.sh --version

Are you trying to install a fresh instance or upgrading an existing one?

Also, could you share the full log of /var/log/chatwoot-setup.log?

**Comment by vishnu-narayanan** [comment]
@bkonia Could you share your instance specs? CPU? RAM?

**Comment by bernardoely** [comment]
same issue on 24.04, I also have 4GB Ram 2 vCPUs.

> > Hey everyone, I was able to replicate this. This is due to the corepack issue and the fixes not being available in `4.0.1`. This will be fixed once the February monthly release is out tomorrow.
> > As a workaround for now, please use `./install.sh --Install develop` to install. This will install the latest `develop` branch, which is the stable release candidate(RC) branch for Feb monthly release.
> 
> Tried this to no avail. see attached screenshots.
> 
> ![Image](https://github.com/user-attachments/assets/69220d80-d27e-420d-be94-5b45f2bc45f4)
> 
> ![Image](https://github.com/user-attachments/assets/84d7d2d2-d454-432a-8fc0-dc14d8f2aacd)

**Comment by vishnu-narayanan** [comment]
@bkonia @bernardoely If possible, please try it on instances with 8GB or more RAM. Also, please set/increase the swap size and try again. 

You can also look at docker deployment to avoid compiling the assets since we have prebuilt images.

**Comment by bernardoely** [comment]
> [@bkonia](https://github.com/bkonia) [@bernardoely](https://github.com/bernardoely) If possible, please try it on instances with 8GB or more RAM. Also, please set/increase the swap size and try again.
> 
> You can also look at docker deployment to avoid compiling the assets since we have prebuilt images.

The swap did the trick! Thanks so much @vishnu-narayanan !

Sharing instructions to create a 8gb swap partition, for those that may not know how to accomplish that:

a) create swap:
Create an 8GB swap file:
```shell
sudo fallocate -l 8G /swapfile
``` 
Set the correct permissions:
```shell
sudo chmod 600 /swapfile
``` 
Format it as swap:
```shell
sudo mkswap /swapfile
``` 
Enable the swap file:
```shell
sudo swapon /swapfile
``` 
Make the swap file permanent (persist after reboot):
```shell
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
``` 
Reboot (not required, just in case, good to check the swap setup):
```shell
sudo reboot
``` 
Verify your new swap configuration:
```shell
free -h
``` 
This should give you 8GB of swap space.

b) install Chatwoot (I used develop branch, with no edits  to install.sh):
```shell
install.sh --Install develop
```

**Comment by eloirobe** [comment]
This works for me 

npm uninstall -g pnpm
npm install -g pnpm@10
