### ISSUE TITLE
Emails account confirmation never received.

### ISSUE THREAD

**Issue by machalex** [chatwoot/chatwoot#1437]
Impossible to receive email confirmation account.
I've installed application both on linuxVM and Heroku.

I've configured SMTP env vars with my own SMTP server config, as describe here: 
https://www.chatwoot.com/docs/environment-variables

But nothing work : email account confirmation never received.

Any Ideas ?

**Comment by pranavrajs** [comment]
@machalex Can you please share server logs? Without that, it is hard to debug this. Also, please share more information like the provider you are using (MailGun/MailChimp) etc.

**Comment by machalex** [comment]
@pranavrajs Sorry for missing information.
the only info I have in logs is : 

2020-11-23T17:23:58.328038+00:00 app[web.1]: I, [2020-11-23T17:23:58.327959 #4]  INFO -- : RoomChannel is transmitting the subscription confirmation

Regarding the SMTP server, I used my own SMTP provider, supplied with my domain provider. I've used these envvars for configuration : 

MAILER_SENDER_EMAIL=my@domain.com
SMTP_PORT=587
SMTP_DOMAIN=domain.com
SMTP_ADDRESS=smtp.domain.com
SMTP_USERNAME=my@domain.com
SMTP_PASSWORD=myPass
SMTP_AUTHENTICATION=login (tried also with "true" ans "plain")
SMTP_ENABLE_STARTTLS_AUTO=true (tried without this env var)

Thanks a lot for your support

**Comment by sojan-official** [comment]
@machalex  could you check in sidekiq whether the workers are working correctly and whether the email job was processed successfully? 

ref: https://github.com/chatwoot/chatwoot/wiki/Creating-a-super-admin-and-accessing-sidekiq

**Comment by machalex** [comment]
@sojan-official Thanks for your support.
Effectively, it seems that sidekiq is not active, and jobs are in queue.

![image](https://user-images.githubusercontent.com/11045936/100014995-89ea8a00-2dd7-11eb-826e-5265187cdab6.png)

What should I do to activate it ?

Thanks in advance.

**Comment by machalex** [comment]
Ok, it seems I've found how to activate sidekiq.
Thanks a lot for your support @sojan-official  @pranavrajs

**Comment by pranavrajs** [comment]
@machalex Closing this as it seems your problem is solved.

**Comment by machalex** [comment]
Hi @sojan-official and @pranavrajs 
Sorry but emails account confirmation still not sent.
Sidekiq is working but jobs not working

![image](https://user-images.githubusercontent.com/11045936/100134515-a09ce980-2e88-11eb-83d1-101d65986efa.png)

Any Ideas ?

**Comment by pranavrajs** [comment]
@machalex This looks like the SMTP credentials are invalid. Could you please tell us what is SMTP provider used here?

**Comment by machalex** [comment]
SMTP provider is same as my domain provider., SMTP is attached to my domain and works perfectly with any mail client as outlook, mail OS or others.... 
But it's not clear about which envvars should I use with my own SMTP provider ?

**Comment by hmnhf** [comment]
@machalex Are you able to [connect to your mail server](https://knowledge.broadcom.com/external/article/164907/test-smtp-authentication-with-messaging.html) and [send an email with telnet](https://linuxconfig.org/send-an-email-using-telnet) on chatwoot's server? If not, there could be some firewall issue. (E.g. port 587 being blocked by ufw or something else.)

**Comment by machalex** [comment]
@hmnhf Hi, yes, I tested it, and I'm effectively able to connect to mail server from chatwoot server.
Still not receive emails for account conformations.

**Comment by machalex** [comment]
Any ideas ?

**Comment by ReactRaja** [comment]
I cant recieve confirmation when using the chatwoot hosted one, let alone the self hosted(which also didnt work for me)

**Comment by sojan-official** [comment]
We have made additional changes and more SMTP configurations available in our previous releases. Just wanted to see if any of that helps or the issue still exists.

**Comment by pranavrajs** [comment]
Closing this as there is no activity for a long time, please feel to reopen this if it is still an issue.
