### ISSUE TITLE
Notifications Internal Server Error

### ISSUE THREAD

**Issue by leo-goss** [chatwoot/chatwoot#2162]
**Describe the bug**

```
/api/v1/accounts/1/notifications?page=1
```
Returns error 500.

**To Reproduce**

1. Log in
2. Click on notifications icon
3. Notification list is empty
4. Console shows Internal Server Error code 500

On a self hosted Linux installation, running latest Chatwoot release.

**Comment by leo-goss** [comment]
This is the log output:

```
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: F, [2021-04-26T21:55:58.632127 #28497] FATAL -- : [617884c4-87c9-4a8f-8d6e-e47f71fe52bf]
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf] ActionView::Template::Error (undefined method `display_id' for nil:NilClass):
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf]      9:     json.array! @notifications do |notification|
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf]     10:       json.id notification.id
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf]     11:       json.notification_type notification.notification_type
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf]     12:       json.push_message_title notification.push_message_title
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf]     13:       # TODO: front end assumes primary actor to be conversation. should fix in future
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf]     14:       if %w[assigned_conversation_new_message conversation_mention].include? notification.notification_type
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf]     15:         json.primary_actor_type 'Conversation'
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf]
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf] app/models/notification.rb:68:in `push_message_title'
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf] app/views/api/v1/accounts/notifications/index.json.jbuilder:12
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf] app/views/api/v1/accounts/notifications/index.json.jbuilder:9
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf] app/views/api/v1/accounts/notifications/index.json.jbuilder:8
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf] app/views/api/v1/accounts/notifications/index.json.jbuilder:1
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf] app/controllers/application_controller.rb:18:in `handle_with_exception'
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
Apr 26 21:55:58 ubuntu chatwoot-web.1[28497]: [617884c4-87c9-4a8f-8d6e-e47f71fe52bf] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
```

**Comment by pranavrajs** [comment]
@leo-goss This was an issue that was solved already. Would you please share the version of Chatwoot using? 

If you are running on an earlier version, we recommend upgrading it to 1.15.1

**Comment by leo-goss** [comment]
upgraded to 1.15.1. The issue persists but logs are different:

```
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: F, [2021-04-27T14:30:02.023295 #31748] FATAL -- : [c0a3d559-ab84-4a3a-acc9-1d85e1433013]
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: [c0a3d559-ab84-4a3a-acc9-1d85e1433013] ActionView::Template::Error (undefined method `display_id' for #<Message:0x0000564195265278>
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: Did you mean?  display):
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: [c0a3d559-ab84-4a3a-acc9-1d85e1433013]      9:     json.array! @notifications do |notification|
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: [c0a3d559-ab84-4a3a-acc9-1d85e1433013]     10:       json.id notification.id
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: [c0a3d559-ab84-4a3a-acc9-1d85e1433013]     11:       json.notification_type notification.notification_type
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: [c0a3d559-ab84-4a3a-acc9-1d85e1433013]     12:       json.push_message_title notification.push_message_title
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: [c0a3d559-ab84-4a3a-acc9-1d85e1433013]     13:       # TODO: front end assumes primary actor to be conversation. should fix in future
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: [c0a3d559-ab84-4a3a-acc9-1d85e1433013]     14:       if %w[assigned_conversation_new_message conversation_mention].include? notification.notification_type
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: [c0a3d559-ab84-4a3a-acc9-1d85e1433013]     15:         json.primary_actor_type 'Conversation'
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: [c0a3d559-ab84-4a3a-acc9-1d85e1433013]
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: [c0a3d559-ab84-4a3a-acc9-1d85e1433013] app/models/notification.rb:72:in `push_message_title'
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: [c0a3d559-ab84-4a3a-acc9-1d85e1433013] app/views/api/v1/accounts/notifications/index.json.jbuilder:12
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: [c0a3d559-ab84-4a3a-acc9-1d85e1433013] app/views/api/v1/accounts/notifications/index.json.jbuilder:9
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: [c0a3d559-ab84-4a3a-acc9-1d85e1433013] app/views/api/v1/accounts/notifications/index.json.jbuilder:8
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: [c0a3d559-ab84-4a3a-acc9-1d85e1433013] app/views/api/v1/accounts/notifications/index.json.jbuilder:1
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: [c0a3d559-ab84-4a3a-acc9-1d85e1433013] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
Apr 27 14:30:02 ubuntu chatwoot-web.1[31748]: [c0a3d559-ab84-4a3a-acc9-1d85e1433013] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
```

**Comment by leo-goss** [comment]
Removed all notifications from DB, seems to have solved the issue and the notifications panel is now working
