### ISSUE TITLE
Slack Integration Works except for attachments/images

### ISSUE THREAD

**Issue by darkpixel** [chatwoot/chatwoot#4639]
I've been using ChatWoot for a few months under Kubernetes (deployed through the Helm chart).  I decided to set up Slack integration today.  It works beautifully....except for images/attachments.

I can text my ChatWoot number and the text comes in to both ChatWoot and Slack.
I can reply from ChatWoot or Slack and it gets back to me.

Sending an image from Slack fails to reach ChatWoot or my phone.  It doesn't appear to matter if it's just an image, or an image with text.

Sending an image from my phone to ChatWoot causes the image to appear in ChatWoot, but not Slack.
If I send image and text from my phone to ChatWoot, both appear in ChatWoot.  In Slack, only the text appears.

I see the following in the ChatWoot logs:
```
I, [2022-05-06T16:59:53.216680 #1]  INFO -- : [d682d6f85311bc48dfda873acac17bf5] [ActiveJob] Enqueued EventDispatcherJob (Job ID: 80b06ea1-4f1a-4f85-910a-db1a6c35eaba) to Sidekiq(events) with arguments: "conversation.updated", Fri, 06 May 2022 16:59:53.212848821 UTC +00:00, {:conversation=>#<GlobalID:0x00007f1f4bab8d28 @uri=#<URI::GID gid://chatwoot/Conversation/39>>, :notifiable_assignee_change=>false}
I, [2022-05-06T16:59:53.583062 #1]  INFO -- : [d682d6f85311bc48dfda873acac17bf5] Completed 500 Internal Server Error in 667ms (ActiveRecord: 26.9ms | Allocations: 14784)
F, [2022-05-06T16:59:53.600977 #1] FATAL -- : [d682d6f85311bc48dfda873acac17bf5]   
[d682d6f85311bc48dfda873acac17bf5] NoMethodError (undefined method `encode' for nil:NilClass):
[d682d6f85311bc48dfda873acac17bf5]   
[d682d6f85311bc48dfda873acac17bf5] lib/integrations/slack/incoming_message_builder.rb:118:in `block in process_attachments'
[d682d6f85311bc48dfda873acac17bf5] lib/integrations/slack/incoming_message_builder.rb:104:in `each'
[d682d6f85311bc48dfda873acac17bf5] lib/integrations/slack/incoming_message_builder.rb:104:in `process_attachments'
[d682d6f85311bc48dfda873acac17bf5] lib/integrations/slack/incoming_message_builder.rb:92:in `create_message'
[d682d6f85311bc48dfda873acac17bf5] lib/integrations/slack/incoming_message_builder.rb:18:in `perform'
[d682d6f85311bc48dfda873acac17bf5] app/controllers/api/v1/integrations/webhooks_controller.rb:4:in `create'
[d682d6f85311bc48dfda873acac17bf5] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
[d682d6f85311bc48dfda873acac17bf5] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
[d682d6f85311bc48dfda873acac17bf5] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
I, [2022-05-06T16:59:53.601515 #1]  INFO -- : source=rack-timeout id=d682d6f85311bc48dfda873acac17bf5 timeout=15000ms service=694ms state=completed
I, [2022-05-06T16:59:57.764113 #1]  INFO -- : RoomChannel#update_presence
I, [2022-05-06T17:00:15.609011 #1]  INFO -- : RoomChannel#update_presence
I, [2022-05-06T17:00:17.763450 #1]  INFO -- : RoomChannel#update_presence
```

**Comment by sojan-official** [comment]
@darkpixel  could you tell us which version of Chatwoot you are using? 
you can view this by accessing `/api/` url

**Comment by danghung-dev** [comment]
I have the same issue when upload image from slack.
I am using version 2.7.0

![image](https://user-images.githubusercontent.com/5670932/180655621-9e44d9bc-482e-405b-b95d-e2fffa4fc3c7.png)

**Comment by sojan-official** [comment]
@tejaswinichile  This was fixed in https://github.com/chatwoot/chatwoot/pull/3022, right ? could you check if the APIs changed?

**Comment by darkpixel** [comment]
I just upgraded to the lasted Helm release and images are still not coming through to Slack.

**Comment by sojan-official** [comment]
@darkpixel Thanks for the update. We will take a look and get back.

**Comment by danilo-dreia** [comment]
Yeah I'm on 2.7.0 and even 2.3 didn't work.

**Comment by markoprodanovic** [comment]
I am having this same problem with the latest version
`{"version":"2.16.1","timestamp":"2023-05-10 16:47:02","queue_services":"ok","data_services":"ok"}`

Is anyone else still experiencing this problem? I'm pretty confident the integration is setup as instructed and text works great!

**Comment by silvaartur** [comment]
Same here!

**Comment by 7hibault** [comment]
I'm facing the same issue here

**Comment by sojan-official** [comment]
@7hibault could you give details of your chatwoot version ?

**Comment by 7hibault** [comment]
@sojan-official yes, of course, sorry about that :) 

v2.17.1

**Comment by sojan-official** [comment]
@7hibault  https://github.com/chatwoot/chatwoot/pull/7179 should fix this. It will be available in the upcoming release.

**Comment by markoprodanovic** [comment]
@sojan-official I'm afraid this issue is still unresolved. 

### Instance Version:
`{"version":"2.18.0","timestamp":"2023-06-22 19:03:10","queue_services":"ok","data_services":"ok"}`

### Tested communication 
Sending png images between Slack -> Telegram. Telegram -> Slack.

### Observed Behaviour
Text can be sent via the Slack integration, images cannot

**Comment by psifertex** [comment]
Same experience here. Finally was able to upgrade to 1.18 in hopes of resolving this bug, not resolved.

**Comment by sojan-official** [comment]
@tejaswinichile, could you give it a check?

**Comment by psifertex** [comment]
Any updates? Still believe this is incorrectly marked as closed. Currently running v2.18.0 and no change in image support in slack has been observed. Uploading via an embedded web chat shows in the chatwoot ui, but not in slack. Uploading on slack side fails to show up in either chatwoot ui or web chat.

**Comment by darkpixel** [comment]
I can't shed anymore light on it. I migrated away to mattermost.
