### ISSUE TITLE
[CW-2877] Issues while running a macro 

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#6014]
- Messages are not available in the Slack if the Slack account is connected. The messages created using Macros are missing.
- The conversation is not removed from the queue if there is a status change 

I believe none of the action cable events/webhook events are working when a macro is executed.

<sub>[CW-2877](https://linear.app/chatwoot/issue/CW-2877/issues-while-running-a-macro)</sub>

**Comment by pranavrajs** [comment]
@tejaswinichile The first issue might have been fixed by this. https://github.com/chatwoot/chatwoot/pull/6093. However, the second still stands.

**Comment by tejaswinichile** [comment]
@pranavrajs 

- The conversation is not removed from the queue if there is a status change

When the Conversation status is updated, it's still not removed from the respective queues. For this, we can add a check inside jobs.

Please confirm if I am in wrong direction.

**Comment by pranavrajs** [comment]
@tejaswinichile I'm not sure what you meant. The issue is that the web socket events return the wrong information or may be out of order, right?

**Comment by pranavrajs** [comment]
@tejaswinichile I'm not able to reproduce it every time. However, it happens more than half of the time when I do it on a daily basis. 

I'm not sure if it dependant on the load or sidekiq backlog. I can probably add a log rocket integration to capture the session.

**Comment by pranavrajs** [comment]
@scmmishra Would you be able to setup a log rocket integration for production Chatwoot? At least my sessions would show this error.

**Comment by pranavrajs** [comment]
Moved to internal tech debt board.
