### ISSUE TITLE
Inbox client handshake failing

### ISSUE THREAD

**Issue by whiteyhat** [chatwoot/chatwoot#702]
## ℹ️ Information
When updating the database values about `Accounts` (So I add my project instead of `Acme.inc`) and other values that are not critical the handshake to reveal who's online fails 

### Code Implemented
![Captura de pantalla 2020-04-09 a las 15 26 42](https://user-images.githubusercontent.com/31220861/78900029-8a1b5c80-7a76-11ea-8e13-44628e95a1a1.png)

### Client logs
<img width="1667" alt="Captura de pantalla 2020-04-09 a las 15 27 31" src="https://user-images.githubusercontent.com/31220861/78900156-b8993780-7a76-11ea-85c1-c4eba9a5fdcb.png">
<img width="355" alt="Captura de pantalla 2020-04-09 a las 15 27 39" src="https://user-images.githubusercontent.com/31220861/78900162-b931ce00-7a76-11ea-99f2-deedbac18942.png">
<img width="765" alt="Captura de pantalla 2020-04-09 a las 15 27 52" src="https://user-images.githubusercontent.com/31220861/78900165-b9ca6480-7a76-11ea-9e1e-82306725eb12.png">

## 🧭 Version 1.3.0

**Comment by whiteyhat** [comment]
@pranavrajs this is quite weird... because If I create a new inbox and attach it to the browser it works, but my previous ones are corrupted... 

Any recommended tables/data to look up in the **database** or **commands** to execute to proceed forward with the issue resolution?

**Comment by pranavrajs** [comment]
It looks like there was an error in data migration, the last release had a critical change in the way we setup users. If you have run rake db:migrate after importing old data, it should be working fine. 

@whiteyhat Could you see if you pull up any log by setting `LOG_LEVEL` to `debug` in environment variables?

**Comment by whiteyhat** [comment]
@pranavrajs `rake:db migrate` did not solve it, but it put out these logs:
```
/app # rake db:migrate
/gems/ruby/2.7.0/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/gems/ruby/2.7.0/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/static.rb:110: warning: The called method `initialize' is defined here
/gems/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/type.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/gems/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/type/adapter_specific_registry.rb:9: warning: The called method `add_modifier' is defined here
/gems/ruby/2.7.0/gems/activemodel-6.0.2.2/lib/active_model/type/integer.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/gems/ruby/2.7.0/gems/activemodel-6.0.2.2/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here
/gems/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/postgresql/oid/specialized_string.rb:12: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/gems/ruby/2.7.0/gems/activemodel-6.0.2.2/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here
/gems/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb:212: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/gems/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:274: warning: The called method `transaction' is defined here
/gems/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/persistence.rb:503: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/gems/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/timestamp.rb:127: warning: The called method `create_or_update' is defined here
```

**Comment by pranavrajs** [comment]
@whiteyhat These are warning from rails core, which is not an issue at the moment. 

@sojan-official / @sony-mathew Please take a look at this issue.

**Comment by subintp** [comment]
@whiteyhat  Can you share the log for the 500 response for inbox members API ?

**Comment by whiteyhat** [comment]
> @whiteyhat Can you share the log for the 500 response for inbox members API ?

@subintp from what service `sidekiq` or `rails`?

**Comment by subintp** [comment]
> > @whiteyhat Can you share the log for the 500 response for inbox members API ?
> 
> @subintp from what service `sidekiq` or `rails`?

Please share from rails for the 500 response

**Comment by whiteyhat** [comment]
```
app/views/api/v1/widget/inbox_members/index.json.jbuilder:3
app/views/api/v1/widget/inbox_members/index.json.jbuilder:2
app/views/api/v1/widget/inbox_members/index.json.jbuilder:1
app/controllers/application_controller.rb:39:in `handle_with_exception'
Started GET "/cable" for 10.0.2.13 at 2020-04-09 15:08:33 +0000
Started GET "/cable/" [WebSocket] for 10.0.2.13 at 2020-04-09 15:08:33 +0000
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
RoomChannel is transmitting the subscription confirmation
RoomChannel is streaming from v2fH2xakwTd38PAiktqFnfJ9
Started GET "/widget?website_token=[FILTERED]" for 98.207.66.148 at 2020-04-09 15:12:24 +0000
Processing by WidgetsController#show as HTML
  Parameters: {"website_token"=>"[FILTERED]"}
  Rendering widgets/show.html.erb
  Rendered widgets/show.html.erb (Duration: 3.7ms | Allocations: 333)
Completed 200 OK in 44ms (Views: 5.8ms | ActiveRecord: 11.1ms | Allocations: 2866)
Started GET "/api/v1/widget/messages?website_token=[FILTERED]" for 98.207.66.148 at 2020-04-09 15:12:25 +0000
Processing by Api::V1::Widget::MessagesController#index as JSON
  Parameters: {"website_token"=>"[FILTERED]"}
Started GET "/api/v1/widget/inbox_members?website_token=[FILTERED]" for 98.207.66.148 at 2020-04-09 15:12:25 +0000
Processing by Api::V1::Widget::InboxMembersController#index as JSON
  Parameters: {"website_token"=>"[FILTERED]"}
  Rendering api/v1/widget/inbox_members/index.json.jbuilder
  Rendering api/v1/widget/messages/index.json.jbuilder
  Rendered api/v1/widget/messages/index.json.jbuilder (Duration: 0.2ms | Allocations: 21)
Completed 200 OK in 25ms (Views: 1.0ms | ActiveRecord: 10.9ms | Allocations: 4573)
  Rendered api/v1/widget/inbox_members/index.json.jbuilder (Duration: 18.2ms | Allocations: 3983)
Completed 500 Internal Server Error in 30ms (ActiveRecord: 10.9ms | Allocations: 5985)
  
ActionView::Template::Error (undefined method `id' for nil:NilClass):
    1: json.payload do
    2:   json.array! @inbox_members do |inbox_member|
    3:     json.id inbox_member.user.id
    4:     json.name inbox_member.user.name
    5:     json.avatar_url inbox_member.user.avatar_url
    6:     json.availability_status inbox_member.user.availability_status
  
app/views/api/v1/widget/inbox_members/index.json.jbuilder:3
app/views/api/v1/widget/inbox_members/index.json.jbuilder:2
app/views/api/v1/widget/inbox_members/index.json.jbuilder:1
app/controllers/application_controller.rb:39:in `handle_with_exception'
Started GET "/cable" for 10.0.2.13 at 2020-04-09 15:12:25 +0000
Started GET "/cable/" [WebSocket] for 10.0.2.13 at 2020-04-09 15:12:25 +0000
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
RoomChannel is transmitting the subscription confirmation
RoomChannel is streaming from fKczMNLTjKhiAPYxEPT4Phvd
Finished "/cable/" [WebSocket] for 10.0.2.13 at 2020-04-09 15:13:19 +0000
RoomChannel stopped streaming from fKczMNLTjKhiAPYxEPT4Phvd
```

**Comment by subintp** [comment]
@whiteyhat Which version you were using before upgrading to 1.3.0 ?

**Comment by whiteyhat** [comment]
I think 1.2.4

**Comment by subintp** [comment]
@whiteyhat  We are not able to reproduce the issue till now. As a quick fix can you try to reset inbox_members?. Step are given below

1. Go to rails console `bundle exec rails c`
2. Run the snippet
`a = Account.find_by_name("Acme Inc")
a.users.each do |u|
  u.inbox_members.destroy_all
end`

PS: This will clear all the inbox members for the given account.

**Comment by whiteyhat** [comment]
That command did not work.

## SOLUTION
But I just delete all entries from the table `inbox_members` and assign the members again from the `rails web app` and it worked!
