### ISSUE TITLE
v3.0 Cant start new conversation [500] with API and whatsup channel

### ISSUE THREAD

**Issue by politsin** [chatwoot/chatwoot#7767]
## 500 ERROR undefined local variable or method `response_sources'

```
rails_1     | I, [2023-08-19T15:02:07.268300 #1]  INFO -- : [7b28cab8-476d-4f9a-b110-5159f342a4b4] Started POST "/api/v1/accounts/2/conversations" for 91.235.x.x at 2023-08-19 15:02:07 +0000
rails_1     | I, [2023-08-19T15:02:07.271071 #1]  INFO -- : [7b28cab8-476d-4f9a-b110-5159f342a4b4] Processing by Api::V1::Accounts::ConversationsController#create as JSON
rails_1     | I, [2023-08-19T15:02:07.271151 #1]  INFO -- : [7b28cab8-476d-4f9a-b110-5159f342a4b4]   Parameters: {"inbox_id"=>2, "contact_id"=>53, "source_id"=>"tg_70721939_15", "additional_attributes"=>{"mail_subject"=>""}, "message"=>{"content"=>"66"}, "assignee_id"=>2, "account_id"=>"2", "conversation"=>{"inbox_id"=>2, "assignee_id"=>2, "contact_id"=>53, "additional_attributes"=>{"mail_subject"=>""}}}
rails_1     | I, [2023-08-19T15:02:07.293481 #1]  INFO -- : [7b28cab8-476d-4f9a-b110-5159f342a4b4] Completed 500 Internal Server Error in 22ms (ActiveRecord: 5.6ms | Allocations: 5408)
rails_1     | F, [2023-08-19T15:02:07.294852 #1] FATAL -- : [7b28cab8-476d-4f9a-b110-5159f342a4b4]
rails_1     | [7b28cab8-476d-4f9a-b110-5159f342a4b4] NameError (undefined local variable or method `response_sources' for #<Inbox id: 2, channel_id: 2, account_id: 2, name: "tg2: ihniumBot", created_at: "2023-04-17 13:38:07.136954000 +0000", updated_at: "2023-05-24 13:18:40.970904000 +0000", channel_type: "Channel::Api", enable_auto_assignment: true, greeting_enabled: false, greeting_message: "", email_address: nil, working_hours_enabled: false, out_of_office_message: nil, timezone: "UTC", enable_email_collect: true, csat_survey_enabled: false, allow_messages_after_resolved: true, auto_assignment_config: {}, lock_to_single_conversation: false, portal_id: nil, sender_name_type: "friendly", business_name: nil>):
rails_1     | [7b28cab8-476d-4f9a-b110-5159f342a4b4]
```

### To Reproduce

1. Open Contact Page or Dialog Contact
2. Click "New Message" Icon
3. Select API or whatsup channel (i have only 2)
4. Put some text and submit
5. --- GOT ERROR
6. See err500

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

**Comment by civilcoder55** [comment]
@politsin 
Try to disable response_bot for the account and try again, it should solve the problem 
If you want to enable the feature, make sure your database is migrated and response_bot related tables are created
![image](https://github.com/chatwoot/chatwoot/assets/58332033/83fe15a1-8982-43a9-9e50-59431b3d73fe)

**Comment by politsin** [comment]
Thank you so much!
That helped me!!!

(I have all the migrations done, but the problem is still there. is there any way to start only this migrations?).

**Comment by mipapo** [comment]
Same issue on 3.0.0 - And with "migrate" I'm getting this error:
```
fatal: not a git repository (or any of the parent directories): .git
Loading Installation config
```

**Comment by vishnu-narayanan** [comment]
@politsin Could you try running the migrations again and restarting the app. Rails will only run pending migrations if any.

**Comment by noezdev** [comment]
Same problem. The only output at running migrations again:

```
RAILS_ENV=production bundle exec rails db:migrate
Loading Installation config
```

But if response_bot is turned on, the error remains.

**Comment by sojan-official** [comment]
response_bot feature requires additional configurations, which we will document in the coming days. 
Please disable the feature until then.
